services:
  - type: web
    name: users-service
    env: docker
    plan: free
    dockerfilePath: ./services/users/Dockerfile

  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerfilePath: ./services/auth/Dockerfile

  - type: web
    name: chats-service
    env: docker
    plan: free
    dockerfilePath: ./services/chats/Dockerfile

  - type: web
    name: messages-service
    env: docker
    plan: free
    dockerfilePath: ./services/messages/Dockerfile
